name: Build

on: [push, pull_request]

jobs:
    mac:
        runs-on: macos-10.15
        steps:
        - uses: actions/checkout@v1

        - name: Setup
          run: brew install libuv sdl2 libpq sdl2_mixer python tree

        - name: Build
          run: |
            mkdir prefix
            prefix=$PWD/prefix
            mkdir build
            cd build
            cmake .. -DHOT_RELOAD_ANIM=0 -DUNITTESTS=OFF -DVISUALTESTS=OFF -DGAMES=OFF -DMAPVIEW=OFF -DAIDEBUG=OFF -DCMAKE_INSTALL_PREFIX=$prefix
            make -j 2
            make install
            tree $prefix
            false
